// Common types
export type Timestamp = Date | string;

// Animal types
export interface Animal {
  id: string;
  type: 'chicken' | 'goat' | 'cow' | 'other';
  name?: string;
  breed?: string;
  quantity: number;
  dateAcquired: Timestamp;
  status: 'active' | 'sold' | 'deceased';
  notes?: string;
  cost?: number;
  aiGeneratedPlan?: CarePlan;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface Chicken extends Animal {
  type: 'chicken';
  eggProduction?: {
    expectedPerDay?: number;
    breed?: string;
  };
}

// Crop types
export interface Crop {
  id: string;
  name: string;
  variety?: string;
  location: 'greenhouse' | 'outdoor' | 'raised-bed' | 'other';
  plantedDate: Timestamp;
  expectedHarvestDate?: Timestamp;
  status: 'planted' | 'growing' | 'harvesting' | 'harvested' | 'failed';
  quantity?: number;
  quantityUnit?: string;
  notes?: string;
  aiGeneratedPlan?: CarePlan;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// Care plan generated by AI
export interface CarePlan {
  summary: string;
  tasks: AIGeneratedTask[];
  tips: string[];
  warnings?: string[];
}

export interface AIGeneratedTask {
  title: string;
  description: string;
  frequency: 'daily' | 'weekly' | 'biweekly' | 'monthly' | 'seasonal' | 'once';
  timing?: string;
  daysFromPlanting?: number; // days after planted/acquired date — used to anchor task due dates
  category: 'feeding' | 'watering' | 'cleaning' | 'health' | 'maintenance' | 'harvesting' | 'other';
}

// Task types
export interface Task {
  id: string;
  title: string;
  description?: string;
  category: 'feeding' | 'watering' | 'cleaning' | 'health' | 'maintenance' | 'harvesting' | 'financial' | 'other';
  relatedTo?: {
    type: 'animal' | 'crop';
    id: string;
    name: string;
  };
  dueDate?: Timestamp;
  isRecurring: boolean;
  frequency?: 'daily' | 'weekly' | 'biweekly' | 'monthly';
  status: 'pending' | 'completed' | 'overdue';
  completedAt?: Timestamp;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// Production log types
export interface ProductionLog {
  id: string;
  type: 'egg-collection' | 'harvest' | 'milk' | 'other';
  relatedTo: {
    type: 'animal' | 'crop';
    id: string;
    name: string;
  };
  quantity: number;
  unit: string;
  date: Timestamp;
  notes?: string;
  quality?: 'excellent' | 'good' | 'fair' | 'poor';
  createdAt: Timestamp;
}

// Financial record types
export interface FinancialRecord {
  id: string;
  type: 'income' | 'expense';
  category: 'feed' | 'supplies' | 'equipment' | 'veterinary' | 'sales' | 'other';
  amount: number;
  description: string;
  relatedTo?: {
    type: 'animal' | 'crop';
    id: string;
    name: string;
  };
  date: Timestamp;
  receiptPhoto?: string; // Storage URL
  createdAt: Timestamp;
}

// Photo documentation
export interface Photo {
  id: string;
  url: string; // Firebase Storage URL
  relatedTo?: {
    type: 'animal' | 'crop' | 'task' | 'general';
    id: string;
    name: string;
  };
  caption?: string;
  date: Timestamp;
  createdAt: Timestamp;
}

// User settings
export interface UserSettings {
  id: string;
  farmName?: string;
  location?: string;
  defaultView: 'dashboard' | 'tasks' | 'livestock' | 'crops';
  notifications: {
    taskReminders: boolean;
    dailySummary: boolean;
  };
  units: {
    temperature: 'fahrenheit' | 'celsius';
    measurement: 'imperial' | 'metric';
  };
}
